export interface Emoji
{
  name : string;
  emoji : string;
};

export const FRUITS = [
        { name: 'tufah', emoji: '🍎' },
        { name: 'banana', emoji: '🍌' },
        { name: '3jaj', emoji: '🍍' },
        { name: 'limon', emoji: '🍋' },
        { name: '7ar', emoji: '🍉' },
        { name: 'frah', emoji: '🍓' },
        { name: 'kaki', emoji: '🍊' },
        { name: '9hesi', emoji: '🍑' },
        { name: '7an9al', emoji: '🍈' },
        { name: 'ber9oq', emoji: '🍒' },
        { name: 'kiwi', emoji: '🥝' },
        { name: 'toffah', emoji: '🍏' },
        { name: '3nabi', emoji: '🍇' },
        { name: 'tamar', emoji: '🌰' },
        { name: 'fig', emoji: '🍈' },
        { name: 'bal3', emoji: '🍍' },
        { name: 'n5awer', emoji: '🍒' },
        { name: 'zibda', emoji: '🥥' },
        { name: 'doum', emoji: '🍉' },
        { name: 'j4ss', emoji: '🍑' },
        { name: 'sefraya', emoji: '🍋' },
        { name: 'mango', emoji: '🥭' },
        { name: 'lem', emoji: '🍋' },
        { name: 'tamarind', emoji: '🌶️' },
        { name: 'ananas', emoji: '🍍' },
        { name: 'jambri', emoji: '🍏' },
        { name: 'tini', emoji: '🍓' },
        { name: 'beres', emoji: '🍒' },
        { name: '3thm', emoji: '🍊' },
        { name: 'pistachio', emoji: '🌰' },
        { name: 'sitrus', emoji: '🍊' }
      ];
      
export const  ANIMALS = [
        { name: '9erd', emoji: '🐒' },
        { name: 'kelb', emoji: '🐶' },
        { name: 'dib', emoji: '🐺' },
        { name: 'mesh', emoji: '🐱' },
        { name: 'nmer', emoji: '🐅' },
        { name: 'fa8d', emoji: '🐆' },
        { name: '3awd', emoji: '🐎' },
        { name: 'tour', emoji: '🐂' },
        { name: 'begra', emoji: '🐄' },
        { name: '7ellouf', emoji: '🐷' },
        { name: 'khenzir', emoji: '🐗' },
        { name: '7awli', emoji: '🐏' },
        { name: 'khrof', emoji: '🐑' },
        { name: 'me3za', emoji: '🐐' },
        { name: 'jmel', emoji: '🐪' },
        { name: 'fil', emoji: '🐘' },
        { name: 'far', emoji: '🐭' },
        { name: 'Tobba', emoji: '🐀' },
        { name: '9nia', emoji: '🐰' },
        { name: 'doub', emoji: '🐻' },
        { name: 'kowala', emoji: '🐨' },
        { name: 'panda', emoji: '🐼' },
        { name: 'djaja', emoji: '🐓' },
        { name: 'fellous', emoji: '🐥' },
        { name: 'bTri9', emoji: '🐧' },
        { name: 'jrana', emoji: '🐸' },
        { name: 'timsa7', emoji: '🐊' },
        { name: 'fekroun', emoji: '🐢' },
        { name: '7ensh', emoji: '🐍' },
        { name: 'tinnin', emoji: '🐉' },
        { name: 'labalen', emoji: '🐳' },
        { name: 'dlfine', emoji: '🐬' },
        { name: '7outa', emoji: '🐟' },
        { name: 'RoTala', emoji: '🐙' },
        { name: 'kokiaj', emoji: '🐚' },
        { name: 'boubbousha', emoji: '🐌' },
        { name: 'douda', emoji: '🐛' },
        { name: 'nemla', emoji: '🐜' },
        { name: 'ne7la', emoji: '🐝' },
        { name: 'koksinil', emoji: '🐞' }
      ];